//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public long RecordID { get; set; }
        public Nullable<long> LeaguesPlayersID { get; set; }
        public Nullable<long> OpponentPlayerID { get; set; }
        public string Stage { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<int> Runs { get; set; }
        public string Overs { get; set; }
        public Nullable<int> Wickets { get; set; }
        public Nullable<int> Fifties { get; set; }
        public Nullable<int> Hundreds { get; set; }
        public Nullable<int> FiveWickets { get; set; }
        public Nullable<int> InningsHigh { get; set; }
        public Nullable<int> OpponentRuns { get; set; }
        public string OpponentOvers { get; set; }
        public Nullable<int> OpponentWickets { get; set; }
        public Nullable<int> OpponentFifties { get; set; }
        public Nullable<int> OpponentHundreds { get; set; }
        public Nullable<int> OpponentFiveWickets { get; set; }
        public Nullable<int> OpponentInningsHigh { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Result { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string FileName { get; set; }
    
        public virtual LeaguesPlayersMaster LeaguesPlayersMaster { get; set; }
        public virtual PlayersMaster PlayersMaster { get; set; }
    }
}
