//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaguesPlayersTeamMaster
    {
        public long RecordID { get; set; }
        public Nullable<long> LeaguesPlayersID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerType { get; set; }
        public string PlayerOrigin { get; set; }
        public string BowlingStyle { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual LeaguesPlayersMaster LeaguesPlayersMaster { get; set; }
    }
}
