//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaguesPlayersMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaguesPlayersMaster()
        {
            this.LeaguesPlayersTeamMaster = new HashSet<LeaguesPlayersTeamMaster>();
            this.Games = new HashSet<Games>();
        }
    
        public long RecordID { get; set; }
        public Nullable<long> LeagueID { get; set; }
        public Nullable<long> PlayerID { get; set; }
        public string TeamName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaguesPlayersTeamMaster> LeaguesPlayersTeamMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Games> Games { get; set; }
        public virtual PlayersMaster PlayersMaster { get; set; }
        public virtual LeaguesMaster LeaguesMaster { get; set; }
    }
}
