//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaguesMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaguesMaster()
        {
            this.Knockouts = new HashSet<Knockouts>();
            this.LeaguesPlayersMaster = new HashSet<LeaguesPlayersMaster>();
            this.LeaguesRulesMaster = new HashSet<LeaguesRulesMaster>();
        }
    
        public long RecordID { get; set; }
        public string Name { get; set; }
        public string Difficulty { get; set; }
        public string Format { get; set; }
        public string Rounds { get; set; }
        public string TeamFormat { get; set; }
        public string MatchTiming { get; set; }
        public string Powerplay { get; set; }
        public string NormalizeSkills { get; set; }
        public string RopeSettings { get; set; }
        public string PitchSettings { get; set; }
        public Nullable<int> WinPoints { get; set; }
        public Nullable<int> LostPoints { get; set; }
        public Nullable<int> ParticipationPoints { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string IsClosed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Winner { get; set; }
        public Nullable<bool> IsGroupLeague { get; set; }
        public Nullable<bool> IsDefaultLeague { get; set; }
        public Nullable<bool> IsCategoryLeague { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knockouts> Knockouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaguesPlayersMaster> LeaguesPlayersMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaguesRulesMaster> LeaguesRulesMaster { get; set; }
    }
}
