//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cricket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CricketEntities : DbContext
    {
        public CricketEntities()
            : base("name=CricketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LeaguesPlayersTeamMaster> LeaguesPlayersTeamMaster { get; set; }
        public virtual DbSet<LeaguesRulesMaster> LeaguesRulesMaster { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LeaguesPlayersMaster> LeaguesPlayersMaster { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Knockouts> Knockouts { get; set; }
        public virtual DbSet<PlayersMaster> PlayersMaster { get; set; }
        public virtual DbSet<LeaguesMaster> LeaguesMaster { get; set; }
    }
}
